name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 1. استدعاء أدوات فلاتر (هذا ما كان ناقصاً)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      
      # 2. بناء ملفات الأندرويد الناقصة (لأنك رفعت فقط ملفات الكود)
      - run: flutter create .
          
      # 3. تحميل المكتبات التي طلبتها (http, url_launcher)
      - run: flutter pub get
      
      # 4. بناء التطبيق
      - run: flutter build apk --release
      
      # 5. تجهيز الرابط للتحميل
      - uses: actions/upload-artifact@v4
        with:
          name: ar-mouse-app
          path: build/app/outputs/flutter-apk/app-release.apk
